app/models.py
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from datetime import datetime

from app import db,login


class Projects(db.Model):
    id = db.Column(db.Integer,primary_key=True)
    project_name = db.Column(db.String(50))
    tasks = db.relationship('Tasks',backref='project',lazy='dynamic')
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))


    def if_name_is_empty(self):
        if self.project_name == "":
            return True
        else:
            return False

    def if_name_is_valid(self):
        if self.project_name != self.project_name.capitalize():
            return False 
        else:
            return True


    def __repr__(self):
        return 'Название проекта - {}'.format(self.project_name)


class Tasks(db.Model):
    id = db.Column(db.Integer,primary_key=True)
    task_name = db.Column(db.String(50))
    task_status = db.Column(db.Boolean)
    task_priority = db.Column(db.Integer)
    date = db.Column(db.String(100)) 
    task_position = db.Column(db.Integer)
    project_id = db.Column(db.Integer,db.ForeignKey('projects.id'))

    def date_time_now(self):
        if self.date == datetime.utcnow():
            return True
        else:
            return False

    def __repr__(self):
        return 'Название таска - {}'.format(self.task_name)



class Users(UserMixin,db.Model):
    id = db.Column(db.Integer,primary_key=True)
    username = db.Column(db.String(50))
    password_hash = db.Column(db.String(64))
    projects = db.relationship('Projects',backref='author',lazy='dynamic')
    
    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return str(self.id)

@login.user_loader
def load_user(id):
    return Users.query.get(int(id))

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired,EqualTo
from app.models import Users

class LoginForm(FlaskForm):
    username = StringField('Логин', validators=[DataRequired('Введенные данные не верны')])
    password = PasswordField('Пароль', validators=[DataRequired('Введенные данные не верны')])
    remember_me = BooleanField('Запомнить меня')
    submit = SubmitField('Войти')

class RegistrationForm(FlaskForm):
    username = StringField('Логин', validators=[DataRequired('Введенные данные не верны')])
    password = PasswordField('Пароль', validators=[DataRequired('Введенные данные не верны')])
    password2 = PasswordField(
        'Повторить пароль', validators=[DataRequired('Введенные данные не верны'), EqualTo('password',message='Пароли не совпадают')])
    submit = SubmitField('Зарегистрироваться')

    def validate_username(self, username):
        user = Users.query.filter_by(username=username.data).first()
        if user is not None:
            raise ValidationError('Логин занят')

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy 
from flask_migrate import Migrate
from flask_login import LoginManager

app = Flask(__name__)
app.config.from_object(Config)
db = SQLAlchemy(app)
migrate = Migrate(app,db)
login = LoginManager(app)
login.login_view = 'login'

from app import views,models

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
from flask import redirect,url_for,jsonify,request,flash
from flask_login import current_user
from . import main
from ..models import Projects,Tasks
from app import db
import ast


@main.route('/add_project',methods=['GET', 'POST'])
def add_project():	
    if request.method=='POST':
        if current_user.is_authenticated:
            proj = Projects(project_name=request.form['name'],user_id=current_user.id)
            db.session.add(proj)
            db.session.commit()
        else:
            proj = Projects(project_name=request.form['name'],user_id='guest')
            db.session.add(proj)
            db.session.commit()  	
    return redirect(url_for('index'))

@main.route('/delete_project/<id>',methods=['GET','POST'])
def delete_project(id):
    delete_id = id
    taskToDelete = Tasks.query.filter_by(project_id=delete_id).delete()
    projToDelete = Projects.query.filter_by(id=delete_id).first()
    db.session.delete(projToDelete)
    db.session.commit()
    return redirect(url_for('index'))

@main.route('/update_project',methods=['GET','POST'])
def update_project():
    update_id = request.form['id']
    project_name = request.form['project_name']
    print(project_name)
    projToUpdate = Projects.query.filter_by(id=update_id).first()
    projToUpdate.project_name = project_name
    db.session.add(projToUpdate)
    db.session.commit()
    return redirect(url_for('index'))

@main.route('/add_task/<id>',methods=['GET','POST'])
def add_task(id):
    if request.method=='POST':
        task = Tasks(task_name=request.form['task_name'],task_status=False,task_priority=request.form['rangeInput'], \
                date=request.form['task_date'],task_position=0,project_id=id)
        db.session.add(task)
        db.session.commit()        
    return redirect(url_for('index'))

@main.route('/delete_task/<id>',methods=['GET','POST'])
def delete_task(id):
    delete_id = id
    print(delete_id)
    taskToDelete = Tasks.query.get(delete_id)
    db.session.delete(taskToDelete)
    db.session.commit()
    return redirect(url_for('index'))

@main.route('/update_task/<id>',methods=['GET','POST'])
def update_task(id):
    old_name = request.form['task_oldname']
    old_date = request.form['task_olddate']
    name = request.form['task_newname']
    date = request.form['task_newdate']
    taskToUpdate = Tasks.query.filter_by(id=id).first()
    taskToUpdate.task_name = name
    taskToUpdate.date = date
    if name=="" and date=="":
        taskToUpdate.date = old_date
        taskToUpdate.task_name = old_name
    elif name=="":
        taskToUpdate.task_name = old_name
        taskToUpdate.task_date = date
    elif date=="":
        taskToUpdate.task_name = name
        taskToUpdate.date = old_date
    else:
        taskToUpdate.task_name = name  
        taskToUpdate.date = date          
    db.session.add(taskToUpdate)
    db.session.commit()
    return redirect(url_for('index'))


@main.route('/task_done/<id>')
def task_done(id):
    taskDone = Tasks.query.get(id)
    taskDone.task_status = True
    db.session.add(taskDone)
    db.session.commit()
    return redirect(url_for('index'))

app/views.py
# -*- coding: utf-8 -*-
from flask import render_template, flash, redirect, url_for, request
from flask_login import login_user, logout_user, current_user, login_required
from app import app,db
from app.forms import LoginForm,RegistrationForm
from app.models import Users,Projects,Tasks


@app.route('/')
@app.route('/index')
def index():
    proj = Projects.query.filter_by(user_id='guest').all()
    task = Tasks.query.order_by(Tasks.task_position).all()
    if current_user.is_authenticated:
        proj = Projects.query.filter_by(user_id=current_user.id).all()
    return render_template('index.html',title='Welcome',proj=proj,task=task)

@app.route('/mytask')
@login_required
def mytask():
    return render_template('mytask.html',title='ToDo')

@app.route('/login',methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = Users.query.filter_by(username=form.username.data).first()
        if user is None or not user.check_password(form.password.data):
            flash('Неверное имя пользователя или пароль')	
            return redirect(url_for('login'))
        login_user(user,remember=form.remember_me.data)
        return redirect(url_for('index'))
    return render_template('login.html', title='Логин', form=form)
    
@app.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('mytask'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = Users(username=form.username.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Теперь войдите в систему')
        return redirect(url_for('login'))
    return render_template('register.html', title='Регистрация', form=form)


@app.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('index'))	

from .main import main as main_blueprint
app.register_blueprint(main_blueprint)

app/templates/_priority.html
<tr data-index="{{ ts.id }}" data-position="{{ ts.position }}">
	<td><a class="btn btn-success" href="{{ url_for('main.task_done',id=ts.id) }}">Завершить</a></td>
	<td colspan="3" id="main_task">
        <form action="{{ url_for('main.update_task',id=ts.id) }}" method="POST">
          <input type="hidden" value="{{ts.task_name}}" name="task_oldname">
          <input type="hidden" value="{{ts.date}}" name="task_olddate">
        <input class="form-control" type="text" placeholder="{{ts.task_name}}" name="task_newname"><input class="form-control" type='date' name="task_newdate" >
        <span>Дата завершения - {{ ts.date }}</span><br>
        <span>Приоритет задачи - {{ ts.task_priority }}</span><br>
       <button class="btn btn-primary" class="form-control-plaintext" type="submit" value="">Обновить</button><a class="btn btn-primary" href="{{ url_for('main.delete_task',id=ts.id) }}">Удалить</button></form></td>
</tr>

app/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<title>{{ title }} | To Do</title>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css">
  <link rel="stylesheet" href="{{ url_for('static',filename='css/datepicker.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static',filename='css/bootstrap.min.css') }}">

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="{{ url_for('index') }}">ToDo</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav ml-auto">
        {% if current_user.is_anonymous %}
        <li class="nav-item"><a class="nav-link" href="{{ url_for('register') }}">Регистрация</a></li>
        <li class="nav-item"><a class="nav-link" href="{{ url_for('login') }}">Войти</a></li>
        {% else %}
        <li class="nav-item"><h3>{{ current_user.username }}</h3></li>
        <li class="nav-item"><a class="nav-link" href="{{ url_for('logout') }}">Выйти</a></li>
        {% endif %}
    </ul>
  </div>
</nav>
<br>
<br>
<br>
{% with messages = get_flashed_messages() %}
{% if messages %}
<ul>
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
{% endwith %}
{% block content %}
{% endblock %}
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

app/templates/index.html
{% extends "base.html" %}
{% block content %}
{% for pr in proj %}
 <div class="jumbotron">
    <center><h1 class="display-3">{{ pr.project_name }}</h1>
    <table class="table table-hover">
      <tbody>
        <tr>
          <td colspan="2">Имя проекта - {{ pr.project_name }}</td>
          <td><a href="{{ url_for('main.delete_project',id=pr.id) }}">удалить</button>  </td>
          <td>
            <form class="form-inline" action="{{ url_for('main.update_project') }}" method="POST">     
              <input type="hidden" value="{{ pr.id }}" name="id">
              <input class="form-control" style=" margin-left: auto; margin-right: 0.1em;" id="project_name" type="text" placeholder="Поменять название" name="project_name">
              <button class="btn btn-primary" type="submit">обновить</button>    
            </form> 
          </td>
        </tr>
      </tbody>
      <tbody>
        <tr class="table-active">
          <th scope="row">+ / -</th>
          <th colspan="3">
            <form  action="{{ url_for('main.add_task',id=pr.id) }}" method="POST">
                <input class="form-control" type="text" name="task_name" placeholder="Название таски">
                <input class="form-control" type='date' name="task_date">
              <input class="form-control" type="number" id="rangeInput" name="rangeInput" min="1" max="5" value="4">
                <input class="btn btn-primary" style=" margin-left: auto; margin-right: 0.1em;" type="submit" value="Добавить">
              </form>
          </th>
        </tr>
        <tr>
             {% for ts in task %}
                    {% if ts.project_id == pr.id %}
                    {% if ts.task_status == False %}
                       {% include '_priority.html' %}
                    {% else %}
                      <tr>
                        <td>
                         <a class="btn btn-primary" href="{{ url_for('main.delete_task',id=ts.id) }}">Удалить</a>
                      </td>
                      <td colspan="3" style="background-color: green; color: white;">
                        Задание - {{ ts.task_name }} - выполнено 
                      </td>
                      </tr>
                    {% endif %}
                    {% endif %}
                  {% endfor %}         
        </tr>
      </tbody>
</table>
</center>
 </div>
<br>
<br>

{% endfor %}
<!-- you here =) -->
<center><button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo">Добавить проект</button></center>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Новый проект</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <form action="{{ url_for('main.add_project') }}" method="POST">
          <div class="form-group">
            <label for="recipient-name" class="col-form-label">Название:</label>
            <input type="text" class="form-control" id="recipient-name" name="name">
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
            <button type="submit" class="btn btn-primary">Создать</button>
          </div>
      </form>
    </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="paper container">
    <h1>Вход в систему</h1>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <div class="form-group">>
            {{ form.username.label }}<br>
            {{ form.username(size=32,class_="form-control") }}<br>
            {% for error in form.username.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </div>
        <div class="form-group">>
            {{ form.password.label }}<br>
            {{ form.password(size=32,class_="form-control") }}<br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </div>
        <div class="form-group">{{ form.remember_me(class_="form-control") }} <center>{{ form.remember_me.label }}</center></div>
        <div class="form-group">{{ form.submit(class_="btn btn-primary") }}</div>
    </form>
</div>
{% endblock %}

app/templates/register.html
{% extends "base.html" %}

{% block content %}
<div class="paper container">
    <h1>Регистрация</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <div class="form-group">>
            {{ form.username.label }}<br>
            {{ form.username(size=32,class_="form-control") }}<br>
            {% for error in form.username.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </div>
        <div class="form-group">>
            {{ form.password.label }}<br>
            {{ form.password(size=32,class_="form-control") }}<br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </div>
        <div class="form-group">>
            {{ form.password2.label }}<br>
            {{ form.password2(size=32,class_="form-control") }}<br>
            {% for error in form.password2.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </div>
        <div class="form-group">{{ form.submit(class_="btn btn-primary") }}</div>
    </form>
</div>
{% endblock %}